<?php

namespace Database\Seeders;

use App\Models\Centro_costo_product;
use Illuminate\Database\Seeder;

class Centro_costo_productSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "1", "stock" => "217.4", "fisico" => "217.4"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "2", "stock" => "645.8", "fisico" => "645.8"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "3", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "4", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "5", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "6", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "7", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "8", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "9", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "10", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "11", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "12", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "13", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "14", "stock" => "103.9", "fisico" => "103.9"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "15", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "16", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "17", "stock" => "35.2", "fisico" => "35.2"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "18", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "19", "stock" => "210.5", "fisico" => "210.5"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "20", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "21", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "22", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "23", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "24", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "25", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "26", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "27", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "28", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "29", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "30", "stock" => "39.7", "fisico" => "39.7"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "31", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "32", "stock" => "66.7", "fisico" => "66.7"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "33", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "34", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "35", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "36", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "37", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "38", "stock" => "40.1", "fisico" => "40.1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "39", "stock" => "3.4", "fisico" => "3.4"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "40", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "41", "stock" => "651.4", "fisico" => "651.4"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "42", "stock" => "346.2", "fisico" => "346.2"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "43", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "44", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "45", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "46", "stock" => "395.1", "fisico" => "395.1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "47", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "48", "stock" => "33", "fisico" => "33"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "49", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "50", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "51", "stock" => "83.7", "fisico" => "83.7"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "52", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "53", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "54", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "55", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "56", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "57", "stock" => "455.3", "fisico" => "455.3"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "58", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "59", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "60", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "61", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "62", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "63", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "64", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "65", "stock" => "44.65", "fisico" => "44.65"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "66", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "67", "stock" => "49.8", "fisico" => "49.8"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "68", "stock" => "39.8", "fisico" => "39.8"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "69", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "70", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "71", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "72", "stock" => "202.5", "fisico" => "202.5"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "73", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "74", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "75", "stock" => "316.7", "fisico" => "316.7"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "76", "stock" => "197.2", "fisico" => "197.2"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "77", "stock" => "158.9", "fisico" => "158.9"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "78", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "79", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "80", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "81", "stock" => "569.7", "fisico" => "569.7"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "82", "stock" => "99.2", "fisico" => "99.2"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "83", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "84", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "85", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "86", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "87", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "88", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "89", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "90", "stock" => "37.1", "fisico" => "37.1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "91", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "92", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "93", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "94", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "95", "stock" => "255.1", "fisico" => "255.1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "96", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "97", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "98", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "99", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "100", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "101", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "102", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "103", "stock" => "38", "fisico" => "38"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "104", "stock" => "26.8", "fisico" => "26.8"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "105", "stock" => "9.9", "fisico" => "9.9"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "106", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "107", "stock" => "2.5", "fisico" => "2.5"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "108", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "109", "stock" => "11.2", "fisico" => "11.2"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "110", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "111", "stock" => "8.8", "fisico" => "8.8"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "112", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "113", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "114", "stock" => "8.8", "fisico" => "8.8"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "115", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "116", "stock" => "209.3", "fisico" => "209.3"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "117", "stock" => "18.2", "fisico" => "18.2"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "118", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "119", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "120", "stock" => "12.2", "fisico" => "12.2"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "121", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "122", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "123", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "124", "stock" => "95", "fisico" => "95"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "125", "stock" => "17.3", "fisico" => "17.3"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "126", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "127", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "128", "stock" => "6.1", "fisico" => "6.1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "129", "stock" => "57", "fisico" => "57"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "130", "stock" => "23.5", "fisico" => "23.5"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "131", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "132", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "133", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "134", "stock" => "90.4", "fisico" => "90.4"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "135", "stock" => "61.4", "fisico" => "61.4"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "136", "stock" => "7.8", "fisico" => "7.8"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "137", "stock" => "66.1", "fisico" => "66.1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "138", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "139", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "140", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "141", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "142", "stock" => "3.6", "fisico" => "3.6"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "143", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "144", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "145", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "146", "stock" => "66.1", "fisico" => "66.1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "147", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "148", "stock" => "17.5", "fisico" => "17.5"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "149", "stock" => "20.7", "fisico" => "20.7"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "150", "stock" => "46.55", "fisico" => "46.55"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "151", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "152", "stock" => "13.7", "fisico" => "13.7"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "153", "stock" => "13.7", "fisico" => "13.7"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "154", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "155", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "156", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "157", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "158", "stock" => "166", "fisico" => "166"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "159", "stock" => "7.9", "fisico" => "7.9"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "160", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "161", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "162", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "163", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "164", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "165", "stock" => "162", "fisico" => "162"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "166", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "167", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "168", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "169", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "170", "stock" => "0.9", "fisico" => "0.9"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "171", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "172", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "173", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "174", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "175", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "176", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "177", "stock" => "3", "fisico" => "3"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "178", "stock" => "6.1", "fisico" => "6.1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "179", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "180", "stock" => "1.4", "fisico" => "1.4"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "181", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "182", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "183", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "184", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "185", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "186", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "187", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "188", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "189", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "190", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "191", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "192", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "193", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "194", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "195", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "196", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "197", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "198", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "199", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "200", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "201", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "202", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "203", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "204", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "205", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "206", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "207", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "208", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "209", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "210", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "211", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "212", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "213", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "214", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "215", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "216", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "217", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "218", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "219", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "220", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "221", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "222", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "223", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "224", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "225", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "226", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "227", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "228", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "229", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "230", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "231", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "232", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "233", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "234", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "235", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "236", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "237", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "238", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "239", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "240", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "241", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "242", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "243", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "244", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "245", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "246", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "247", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "248", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "249", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "250", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "251", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "252", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "253", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "254", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "255", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "256", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "1", "products_id" => "257", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();

        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "1", "stock" => "11.57", "fisico" => "11.57"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "2", "stock" => "12.79", "fisico" => "12.79"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "3", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "4", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "5", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "6", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "7", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "8", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "9", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "10", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "11", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "12", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "13", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "14", "stock" => "10.9", "fisico" => "10.9"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "15", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "16", "stock" => "5.88", "fisico" => "5.88"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "17", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "18", "stock" => "15.33", "fisico" => "15.33"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "19", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "20", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "21", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "22", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "23", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "24", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "25", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "26", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "27", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "28", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "29", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "30", "stock" => "0.635", "fisico" => "0.635"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "31", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "32", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "33", "stock" => "1.925", "fisico" => "1.925"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "34", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "35", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "36", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "37", "stock" => "3.08", "fisico" => "3.08"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "38", "stock" => "0.725", "fisico" => "0.725"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "39", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "40", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "41", "stock" => "4.44", "fisico" => "4.44"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "42", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "43", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "44", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "45", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "46", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "47", "stock" => "6.95", "fisico" => "6.95"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "48", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "49", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "50", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "51", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "52", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "53", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "54", "stock" => "25.5", "fisico" => "25.5"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "55", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "56", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "57", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "58", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "59", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "60", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "61", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "62", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "63", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "64", "stock" => "1.2", "fisico" => "1.2"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "65", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "66", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "67", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "68", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "69", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "70", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "71", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "72", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "73", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "74", "stock" => "2.57", "fisico" => "2.57"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "75", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "76", "stock" => "11.05", "fisico" => "11.05"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "77", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "78", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "79", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "80", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "81", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "82", "stock" => "22.12", "fisico" => "22.12"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "83", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "84", "stock" => "9.45", "fisico" => "9.45"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "85", "stock" => "1.65", "fisico" => "1.65"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "86", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "87", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "88", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "89", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "90", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "91", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "92", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "93", "stock" => "5", "fisico" => "5"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "94", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "95", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "96", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "97", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "98", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "99", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "100", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "101", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "102", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "103", "stock" => "2.25", "fisico" => "2.25"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "104", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "105", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "106", "stock" => "1.02", "fisico" => "1.02"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "107", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "108", "stock" => "10.17", "fisico" => "10.17"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "109", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "110", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "111", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "112", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "113", "stock" => "1.18", "fisico" => "1.18"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "114", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "115", "stock" => "0.96", "fisico" => "0.96"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "116", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "117", "stock" => "12.155", "fisico" => "12.155"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "118", "stock" => "6.95", "fisico" => "6.95"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "119", "stock" => "5.3", "fisico" => "5.3"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "120", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "121", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "122", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "123", "stock" => "0.565", "fisico" => "0.565"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "124", "stock" => "4.62", "fisico" => "4.62"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "125", "stock" => "1.225", "fisico" => "1.225"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "126", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "127", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "128", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "129", "stock" => "0.675", "fisico" => "0.675"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "130", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "131", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "132", "stock" => "4.44", "fisico" => "4.44"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "133", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "134", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "135", "stock" => "4.68", "fisico" => "4.68"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "136", "stock" => "26.8", "fisico" => "26.8"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "137", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "138", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "139", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "140", "stock" => "0.4", "fisico" => "0.4"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "141", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "142", "stock" => "10.375", "fisico" => "10.375"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "143", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "144", "stock" => "0.54", "fisico" => "0.54"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "145", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "146", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "147", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "148", "stock" => "16.63", "fisico" => "16.63"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "149", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "150", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "151", "stock" => "1.34", "fisico" => "1.34"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "152", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "153", "stock" => "5.6", "fisico" => "5.6"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "154", "stock" => "0.7", "fisico" => "0.7"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "155", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "156", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "157", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "158", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "159", "stock" => "7.935", "fisico" => "7.935"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "160", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "161", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "162", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "163", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "164", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "165", "stock" => "0.975", "fisico" => "0.975"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "166", "stock" => "6.195", "fisico" => "6.195"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "167", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "168", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "169", "stock" => "4.63", "fisico" => "4.63"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "170", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "171", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "172", "stock" => "0.905", "fisico" => "0.905"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "173", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "174", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "175", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "176", "stock" => "6.84", "fisico" => "6.84"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "177", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "178", "stock" => "2.88", "fisico" => "2.88"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "179", "stock" => "2.635", "fisico" => "2.635"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "180", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "181", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "182", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "183", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "184", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "185", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "186", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "187", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "188", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "189", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "190", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "191", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "192", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "193", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "194", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "195", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "196", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "197", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "198", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "199", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "200", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "201", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "202", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "203", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "204", "stock" => "23", "fisico" => "23"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "205", "stock" => "2", "fisico" => "2"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "206", "stock" => "22", "fisico" => "22"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "207", "stock" => "4", "fisico" => "4"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "208", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "209", "stock" => "7", "fisico" => "7"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "210", "stock" => "40", "fisico" => "40"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "211", "stock" => "23", "fisico" => "23"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "212", "stock" => "41", "fisico" => "41"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "213", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "214", "stock" => "16", "fisico" => "16"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "215", "stock" => "31", "fisico" => "31"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "216", "stock" => "28", "fisico" => "28"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "217", "stock" => "32", "fisico" => "32"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "218", "stock" => "19", "fisico" => "19"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "219", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "220", "stock" => "31", "fisico" => "31"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "221", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "222", "stock" => "3", "fisico" => "3"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "223", "stock" => "3", "fisico" => "3"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "224", "stock" => "2", "fisico" => "2"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "225", "stock" => "3", "fisico" => "3"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "226", "stock" => "3", "fisico" => "3"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "227", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "228", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "229", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "230", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "231", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "232", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "233", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "234", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "235", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "236", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "237", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "238", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "239", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "240", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "241", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "242", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "243", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "244", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "245", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "246", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "247", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "248", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "249", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "250", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "251", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "252", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "253", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "254", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "255", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "256", "stock" => "1", "fisico" => "1"]);
        $Centro_costo_product->save();
        $Centro_costo_product = new Centro_costo_product(["centrocosto_id" => "2", "products_id" => "257", "stock" => "10", "fisico" => "0"]);
        $Centro_costo_product->save();
    }
}
