<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //RES

        $product = new Product(["code" => "RE0001", "barcode" => "99123456", "name" => "BOLA DE PIERNA", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "1", "unitofmeasure_id" => "1", "cost" => "10000", "price_fama" => "24000", "price_insti" => "24000", "price_horeca" => "28000", "price_hogar" => "28000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0002", "barcode" => "99123457", "name" => "BRAZO COMPLETO", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "10500", "price_fama" => "20500", "price_insti" => "20500", "price_horeca" => "0", "price_hogar" => "19500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0003", "barcode" => "99123458", "name" => "ASAR ESPECIAL", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "11000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "27000", "price_hogar" => "27000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0004", "barcode" => "99123459", "name" => "BOLA DE BRAZO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "11500", "price_fama" => "23000", "price_insti" => "23000", "price_horeca" => "0", "price_hogar" => "21000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0005", "barcode" => "99123460", "name" => "CARNE BLANDA ASAR DE RES", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0006", "barcode" => "99123461", "name" => "CARNE FINA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "26000", "price_hogar" => "26000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0007", "barcode" => "99123462", "name" => "CARNE GOULASH", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "23000", "price_hogar" => "23000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0008", "barcode" => "99123463", "name" => "LOMO DE BRAZO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "23000", "price_insti" => "23000", "price_horeca" => "0", "price_hogar" => "21000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0009", "barcode" => "99123464", "name" => "MINI PUNTA DE ANCA (BRAZO)", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "13000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "26000", "price_hogar" => "26000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0010", "barcode" => "99123465", "name" => "MOLINA ESPECIAL BRAZO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "13500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0011", "barcode" => "99123466", "name" => "PALETERO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "14000", "price_fama" => "23000", "price_insti" => "23000", "price_horeca" => "0", "price_hogar" => "23000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0012", "barcode" => "99123467", "name" => "SEBO BRAZO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "2800", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0013", "barcode" => "99123468", "name" => "CADERA COMPLETA", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "3", "unitofmeasure_id" => "1", "cost" => "10000", "price_fama" => "24500", "price_insti" => "24500", "price_horeca" => "0", "price_hogar" => "24000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0014", "barcode" => "99123469", "name" => "CADERA SIN", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "3", "unitofmeasure_id" => "1", "cost" => "10500", "price_fama" => "24000", "price_insti" => "24000", "price_horeca" => "28000", "price_hogar" => "28000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0015", "barcode" => "99123470", "name" => "MINICHURRASCO DE CADERA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "3", "unitofmeasure_id" => "1", "cost" => "11000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "28000", "price_hogar" => "28000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0016", "barcode" => "99123471", "name" => "PUNTA DE ANCA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "3", "unitofmeasure_id" => "1", "cost" => "11500", "price_fama" => "29000", "price_insti" => "29000", "price_horeca" => "36000", "price_hogar" => "36000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0017", "barcode" => "99123472", "name" => "SEBO DE CADERA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "3", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "2800", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0018", "barcode" => "99123473", "name" => "CHATA COMPLETA", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "29500", "price_insti" => "29500", "price_horeca" => "35000", "price_hogar" => "35000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0019", "barcode" => "99123474", "name" => "BEEF CHORIZO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "41000", "price_hogar" => "41000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0020", "barcode" => "99123475", "name" => "BIFE DE CHORIZO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0021", "barcode" => "99123476", "name" => "CHATA RECORTADA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "13000", "price_fama" => "31000", "price_insti" => "31000", "price_horeca" => "0", "price_hogar" => "31000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0022", "barcode" => "99123477", "name" => "CHURRASCO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "13500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "35000", "price_hogar" => "35000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0023", "barcode" => "99123478", "name" => "NEW YORK STEAK", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "14000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "41000", "price_hogar" => "41000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0024", "barcode" => "99123479", "name" => "OJO DE BIFE", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "40000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0025", "barcode" => "99123480", "name" => "PUNTA DE CHATA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "10000", "price_fama" => "30000", "price_insti" => "30000", "price_horeca" => "0", "price_hogar" => "30000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0026", "barcode" => "99123481", "name" => "RIBEYE STEAK", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "10500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "41000", "price_hogar" => "41000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0027", "barcode" => "99123482", "name" => "ROSBIF DE RES", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "11000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "41000", "price_hogar" => "41000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0028", "barcode" => "99123483", "name" => "T BONE", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "11500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "42000", "price_hogar" => "42000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0029", "barcode" => "99123484", "name" => "TOMAHAWK", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "35000", "price_insti" => "35000", "price_horeca" => "43000", "price_hogar" => "43000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0030", "barcode" => "99123485", "name" => "CHOCOZUELA", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "5", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "5000", "price_hogar" => "5000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0031", "barcode" => "99123486", "name" => "RILA - CHOCOZUELA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "5", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "3500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0032", "barcode" => "99123487", "name" => "UBRE", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "5", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "3500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0033", "barcode" => "99123488", "name" => "COGOTE", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "6", "unitofmeasure_id" => "1", "cost" => "13000", "price_fama" => "19500", "price_insti" => "19500", "price_horeca" => "0", "price_hogar" => "19000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0034", "barcode" => "99123489", "name" => "MOLIDA 80/20", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "6", "unitofmeasure_id" => "1", "cost" => "13500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "25000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0035", "barcode" => "99123490", "name" => "MOLIDA 90/10", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "6", "unitofmeasure_id" => "1", "cost" => "14000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "26000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0036", "barcode" => "99123491", "name" => "SEBO DE COGOTE", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "6", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "2800", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0037", "barcode" => "99123492", "name" => "COLA ENTERA", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "7", "unitofmeasure_id" => "1", "cost" => "10000", "price_fama" => "18000", "price_insti" => "18000", "price_horeca" => "0", "price_hogar" => "18000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0038", "barcode" => "99123493", "name" => "NUDO DE COLA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "7", "unitofmeasure_id" => "1", "cost" => "10500", "price_fama" => "22000", "price_insti" => "22000", "price_horeca" => "28400", "price_hogar" => "28400", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0039", "barcode" => "99123494", "name" => "SEBO DE COLA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "7", "unitofmeasure_id" => "1", "cost" => "11000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "2800", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0040", "barcode" => "99123495", "name" => "COSTILLA COMPLETA", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "11500", "price_fama" => "17000", "price_insti" => "17000", "price_horeca" => "0", "price_hogar" => "17000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0041", "barcode" => "99123496", "name" => "COSTILLA DE RES", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "16000", "price_hogar" => "16000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0042", "barcode" => "99123497", "name" => "COSTILLA ESPECIAL", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "18000", "price_hogar" => "18000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0043", "barcode" => "99123498", "name" => "COSTILLA PREMIUN", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "19000", "price_hogar" => "19000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0044", "barcode" => "99123499", "name" => "COSTILLA TRASERA (CANASTO)", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "15000", "price_insti" => "15000", "price_horeca" => "0", "price_hogar" => "15000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0045", "barcode" => "99123500", "name" => "FALDA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "13000", "price_fama" => "23000", "price_insti" => "23000", "price_horeca" => "25000", "price_hogar" => "25000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0046", "barcode" => "99123501", "name" => "PALOMILLA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "13500", "price_fama" => "22500", "price_insti" => "22500", "price_horeca" => "25000", "price_hogar" => "25000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0047", "barcode" => "99123502", "name" => "SOBREBARRIGA DELGADA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "14000", "price_fama" => "23000", "price_insti" => "23000", "price_horeca" => "26000", "price_hogar" => "26000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0048", "barcode" => "99123503", "name" => "VACIO ENTERO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0049", "barcode" => "99123504", "name" => "SEBO DE COSTILLA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "10000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "2800", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0050", "barcode" => "99123505", "name" => "COSTILLA DELANTERA", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "9", "unitofmeasure_id" => "1", "cost" => "10500", "price_fama" => "19000", "price_insti" => "19000", "price_horeca" => "0", "price_hogar" => "17000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0051", "barcode" => "99123506", "name" => "ASADO DE TIRA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "9", "unitofmeasure_id" => "1", "cost" => "11000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "22000", "price_hogar" => "22000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0052", "barcode" => "99123507", "name" => "CREADILLA", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "10", "unitofmeasure_id" => "1", "cost" => "11500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0053", "barcode" => "99123508", "name" => "DECOMISO DE RES", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "11", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "600", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0054", "barcode" => "99123509", "name" => "DESCARGUE COMPLETO", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "19500", "price_insti" => "19500", "price_horeca" => "0", "price_hogar" => "19000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0055", "barcode" => "99123510", "name" => "CARNE BLANDA PARA ASAR", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "23800", "price_hogar" => "23800", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0056", "barcode" => "99123511", "name" => "CARNE FINA PARA ASAR", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "23000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0057", "barcode" => "99123512", "name" => "CARNE PARA SUDAR DE RES", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "13000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "24000", "price_hogar" => "24000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0058", "barcode" => "99123513", "name" => "MILANESA DE RES", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "13500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "22000", "price_hogar" => "22000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0059", "barcode" => "99123514", "name" => "MORRILLO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "14000", "price_fama" => "22000", "price_insti" => "22000", "price_horeca" => "0", "price_hogar" => "20000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0060", "barcode" => "99123515", "name" => "MOLIDA ESPECIAL DESCARGUE", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0061", "barcode" => "99123516", "name" => "CARNES PARA GOULASH", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "10000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0062", "barcode" => "99123517", "name" => "SEBO DESCARGUE", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "10500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "2800", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0063", "barcode" => "99123518", "name" => "GORDO- GRASA DE PECHO", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "13", "unitofmeasure_id" => "1", "cost" => "11000", "price_fama" => "6000", "price_insti" => "6000", "price_horeca" => "0", "price_hogar" => "4800", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0064", "barcode" => "99123519", "name" => "HUESO CARNUDO", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "14", "unitofmeasure_id" => "1", "cost" => "11500", "price_fama" => "6000", "price_insti" => "6000", "price_horeca" => "5000", "price_hogar" => "5000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0065", "barcode" => "99123520", "name" => "HUESO CARNUDO ESPECIAL", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "14", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "6000", "price_insti" => "6000", "price_horeca" => "7000", "price_hogar" => "7000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0066", "barcode" => "99123521", "name" => "HUESO DE AGUJA", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "15", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "13000", "price_insti" => "13000", "price_horeca" => "0", "price_hogar" => "13000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0067", "barcode" => "99123522", "name" => "HUESO DE PALETA", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "16", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "27550", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0068", "barcode" => "99123523", "name" => "HUESO PALETA RES", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "16", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "21000", "price_insti" => "21000", "price_horeca" => "0", "price_hogar" => "21000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0069", "barcode" => "99123524", "name" => "HUESO DE PECHO CORRIENTE", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "17", "unitofmeasure_id" => "1", "cost" => "13000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "3500", "price_hogar" => "3500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0070", "barcode" => "99123525", "name" => "HUESO POROSO", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "18", "unitofmeasure_id" => "1", "cost" => "13500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "900", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0071", "barcode" => "99123526", "name" => "LOMO ENTERO", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "19", "unitofmeasure_id" => "1", "cost" => "14000", "price_fama" => "38000", "price_insti" => "38000", "price_horeca" => "0", "price_hogar" => "38000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0072", "barcode" => "99123527", "name" => "LOMO LIMPIO SIN CORDON", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "19", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "50000", "price_insti" => "50000", "price_horeca" => "42000", "price_hogar" => "42000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0073", "barcode" => "99123528", "name" => "CORDON DE LOMO FINO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "19", "unitofmeasure_id" => "1", "cost" => "10000", "price_fama" => "50000", "price_insti" => "50000", "price_horeca" => "42000", "price_hogar" => "42000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0074", "barcode" => "99123529", "name" => "MOTA", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "20", "unitofmeasure_id" => "1", "cost" => "10500", "price_fama" => "14000", "price_insti" => "14000", "price_horeca" => "0", "price_hogar" => "14000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0075", "barcode" => "99123530", "name" => "MOLIDA CORRIENTE", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "20", "unitofmeasure_id" => "1", "cost" => "11000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "17000", "price_hogar" => "17000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0076", "barcode" => "99123531", "name" => "MURILLO", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "21", "unitofmeasure_id" => "1", "cost" => "11500", "price_fama" => "18000", "price_insti" => "18000", "price_horeca" => "23000", "price_hogar" => "23000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0077", "barcode" => "99123532", "name" => "GOULASH DE MURILLO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "21", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0078", "barcode" => "99123533", "name" => "MURILLO PEPINO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "21", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "19500", "price_insti" => "19500", "price_horeca" => "0", "price_hogar" => "19500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0079", "barcode" => "99123534", "name" => "SEBO DE MURILLO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "21", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "2800", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0080", "barcode" => "99123535", "name" => "PACHAS", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "22", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "23500", "price_insti" => "23500", "price_horeca" => "0", "price_hogar" => "23500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0081", "barcode" => "99123536", "name" => "BOTA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "22", "unitofmeasure_id" => "1", "cost" => "13000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "28000", "price_hogar" => "28000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0082", "barcode" => "99123537", "name" => "BOTA COMPLETA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "22", "unitofmeasure_id" => "1", "cost" => "13500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0083", "barcode" => "99123538", "name" => "CENTRO AL VACIO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "22", "unitofmeasure_id" => "1", "cost" => "14000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0084", "barcode" => "99123539", "name" => "CENTRO DE PIERNA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "22", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "24000", "price_insti" => "24000", "price_horeca" => "28000", "price_hogar" => "28000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0085", "barcode" => "99123540", "name" => "MUCHACHO DE RES", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "22", "unitofmeasure_id" => "1", "cost" => "10000", "price_fama" => "27000", "price_insti" => "27000", "price_horeca" => "28000", "price_hogar" => "28000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0086", "barcode" => "99123541", "name" => "SIRLOIN DE RES", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "22", "unitofmeasure_id" => "1", "cost" => "10500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "33000", "price_hogar" => "33000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0087", "barcode" => "99123542", "name" => "TORTUGA(CAMPANA)", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "22", "unitofmeasure_id" => "1", "cost" => "11000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0088", "barcode" => "99123543", "name" => "SEBO DE PACHAS", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "22", "unitofmeasure_id" => "1", "cost" => "11500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "2800", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0089", "barcode" => "99123544", "name" => "PECHO", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "23", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "26000", "price_hogar" => "26000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0090", "barcode" => "99123545", "name" => "CARNE PARA DESMECHAR", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "23", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "24000", "price_hogar" => "24000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0091", "barcode" => "99123546", "name" => "PECHO CON", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "23", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "22000", "price_insti" => "22000", "price_horeca" => "0", "price_hogar" => "21000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0092", "barcode" => "99123547", "name" => "PECHO SIN", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "23", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "22500", "price_insti" => "22500", "price_horeca" => "0", "price_hogar" => "22000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0093", "barcode" => "99123548", "name" => "SOBREBARRIGA GRUESA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "23", "unitofmeasure_id" => "1", "cost" => "13000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "25000", "price_hogar" => "25000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0094", "barcode" => "99123549", "name" => "TAPA", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "23", "unitofmeasure_id" => "1", "cost" => "13500", "price_fama" => "22000", "price_insti" => "22000", "price_horeca" => "0", "price_hogar" => "21000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0095", "barcode" => "99123550", "name" => "SEBO DE PECHO", "stock" => "0", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "23", "unitofmeasure_id" => "1", "cost" => "14000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "2800", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0096", "barcode" => "99123551", "name" => "PIEL DE RES", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "24", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "800", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0097", "barcode" => "99123552", "name" => "RES EN CANAL", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "25", "unitofmeasure_id" => "1", "cost" => "14833", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0098", "barcode" => "99123553", "name" => "RES EN PIE", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "26", "unitofmeasure_id" => "1", "cost" => "13500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0099", "barcode" => "99123554", "name" => "VIRIL", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "27", "unitofmeasure_id" => "1", "cost" => "14000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "35000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "RE0100", "barcode" => "99123555", "name" => "VISCERAS DE RES", "stock" => "0", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "28", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "340000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0001", "barcode" => "223456755", "name" => "TOCINO BARRIGA", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "29", "unitofmeasure_id" => "1", "cost" => "13500", "price_fama" => "17000", "price_insti" => "17000", "price_horeca" => "20200", "price_hogar" => "20200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0002", "barcode" => "223456756", "name" => "BONDIOLA", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "30", "unitofmeasure_id" => "1", "cost" => "14000", "price_fama" => "17000", "price_insti" => "17000", "price_horeca" => "21200", "price_hogar" => "21200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0003", "barcode" => "223456757", "name" => "BRAZO DE CERDO PERNIL", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "31", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "17000", "price_insti" => "17000", "price_horeca" => "21200", "price_hogar" => "21200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0004", "barcode" => "223456758", "name" => "CHULETA DE BRAZO", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "33", "unitofmeasure_id" => "1", "cost" => "10000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "21200", "price_hogar" => "21200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0005", "barcode" => "223456759", "name" => "GOULASH DE CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "33", "unitofmeasure_id" => "1", "cost" => "10500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "21200", "price_hogar" => "21200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0006", "barcode" => "223456760", "name" => "PULPA DE BRAZO CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "33", "unitofmeasure_id" => "1", "cost" => "11000", "price_fama" => "17000", "price_insti" => "17000", "price_horeca" => "21200", "price_hogar" => "21200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0007", "barcode" => "223456761", "name" => "TOCINO CORRIENTE BRAZO", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "33", "unitofmeasure_id" => "1", "cost" => "11500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0008", "barcode" => "223456762", "name" => "CABEZA DE CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "32", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "4500", "price_insti" => "4500", "price_horeca" => "3200", "price_hogar" => "3200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0009", "barcode" => "223456763", "name" => "CERDO EN CANAL", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "33", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0010", "barcode" => "223456764", "name" => "OSOBUCO Y CODITO", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "34", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "14200", "price_hogar" => "14200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0011", "barcode" => "223456765", "name" => "COSTILOMO COMPLETO", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "35", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "14200", "price_hogar" => "14200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0012", "barcode" => "223456766", "name" => "CHULETA DE LOMO", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "37", "unitofmeasure_id" => "1", "cost" => "13000", "price_fama" => "18000", "price_insti" => "18000", "price_horeca" => "0", "price_hogar" => "18000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0013", "barcode" => "223456767", "name" => "COSTILLA DE CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "37", "unitofmeasure_id" => "1", "cost" => "13500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "23200", "price_hogar" => "23200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0014", "barcode" => "223456768", "name" => "COSTILLA SPARICK", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "37", "unitofmeasure_id" => "1", "cost" => "14000", "price_fama" => "18000", "price_insti" => "18000", "price_horeca" => "21200", "price_hogar" => "21200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0015", "barcode" => "223456769", "name" => "LOMO DE CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "37", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "22200", "price_hogar" => "22200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0016", "barcode" => "223456770", "name" => "MILANESA DE CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "37", "unitofmeasure_id" => "1", "cost" => "10000", "price_fama" => "20000", "price_insti" => "20000", "price_horeca" => "23200", "price_hogar" => "23200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0017", "barcode" => "223456771", "name" => "TOCINO CORRIENTE DORSAL", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "37", "unitofmeasure_id" => "1", "cost" => "10500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "21200", "price_hogar" => "21200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0018", "barcode" => "223456772", "name" => "DECOMISO DE CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "36", "unitofmeasure_id" => "1", "cost" => "11000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "600", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0019", "barcode" => "223456773", "name" => "TOCINO CORRIENTE DORSAL", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "37", "unitofmeasure_id" => "1", "cost" => "11500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0020", "barcode" => "223456774", "name" => "EMPELLA - DESPALME", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "38", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0021", "barcode" => "223456775", "name" => "ESPINAZO DE CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "39", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "9000", "price_insti" => "9000", "price_horeca" => "11200", "price_hogar" => "11200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0022", "barcode" => "223456776", "name" => "COLAS DE CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "42", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "12200", "price_hogar" => "12200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0023", "barcode" => "223456777", "name" => "ESPINAZO DE CERDO ESPECIAL", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "42", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0024", "barcode" => "223456778", "name" => "HUESO POROSO DE CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "40", "unitofmeasure_id" => "1", "cost" => "13000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0025", "barcode" => "223456779", "name" => "MOTA DE CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "41", "unitofmeasure_id" => "1", "cost" => "13500", "price_fama" => "10000", "price_insti" => "10000", "price_horeca" => "0", "price_hogar" => "7750", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0026", "barcode" => "223456780", "name" => "PANCETA", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "42", "unitofmeasure_id" => "1", "cost" => "14000", "price_fama" => "22000", "price_insti" => "22000", "price_horeca" => "22200", "price_hogar" => "22200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0027", "barcode" => "223456781", "name" => "MATAMBRE", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "46", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0028", "barcode" => "223456782", "name" => "TOCINO PAPADA", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "43", "unitofmeasure_id" => "1", "cost" => "10000", "price_fama" => "15000", "price_insti" => "15000", "price_horeca" => "17200", "price_hogar" => "17200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0029", "barcode" => "223456783", "name" => "TOCINO CORRIENTE PERNIL", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "44", "unitofmeasure_id" => "1", "cost" => "10500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0030", "barcode" => "223456784", "name" => "CHULETA DE PIERNA", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "48", "unitofmeasure_id" => "1", "cost" => "11000", "price_fama" => "18000", "price_insti" => "18000", "price_horeca" => "22200", "price_hogar" => "22200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0031", "barcode" => "223456785", "name" => "PULPA DE PIERNA CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "48", "unitofmeasure_id" => "1", "cost" => "11500", "price_fama" => "18000", "price_insti" => "18000", "price_horeca" => "22200", "price_hogar" => "22200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0032", "barcode" => "223456786", "name" => "SIRLOIN DE CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "48", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "19000", "price_insti" => "19000", "price_horeca" => "21200", "price_hogar" => "21200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0033", "barcode" => "223456787", "name" => "SOLOMITO DE CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "48", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "23200", "price_hogar" => "23200", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "CE0034", "barcode" => "223456788", "name" => "PEZUÑA DE CERDO", "stock" => "0", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "45", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "9000", "price_insti" => "9000", "price_horeca" => "10600", "price_hogar" => "10600", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0001", "barcode" => "323456689", "name" => "ALAS CON COSTILLAR", "stock" => "0", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "46", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "8500", "price_insti" => "8500", "price_horeca" => "8000", "price_hogar" => "8000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0002", "barcode" => "323456690", "name" => "ALAS SIN COSTILLAR", "stock" => "0", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "47", "unitofmeasure_id" => "1", "cost" => "10000", "price_fama" => "9500", "price_insti" => "9500", "price_horeca" => "9000", "price_hogar" => "9000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0003", "barcode" => "323456691", "name" => "DECOMISO DE POLLO", "stock" => "0", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "48", "unitofmeasure_id" => "1", "cost" => "10500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "600", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0004", "barcode" => "323456692", "name" => "MIXTO DE POLLO", "stock" => "0", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "49", "unitofmeasure_id" => "1", "cost" => "11000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0005", "barcode" => "323456693", "name" => "PECHUGA BLANCA", "stock" => "0", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "50", "unitofmeasure_id" => "1", "cost" => "11500", "price_fama" => "15500", "price_insti" => "15500", "price_horeca" => "15000", "price_hogar" => "15000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0006", "barcode" => "323456694", "name" => "FILETE DE PECHUGA", "stock" => "0", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "54", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "21000", "price_hogar" => "21000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0007", "barcode" => "323456695", "name" => "HUESOS DE POLLO", "stock" => "0", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "54", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0008", "barcode" => "323456696", "name" => "PIEL DE POLLO", "stock" => "0", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "54", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0009", "barcode" => "323456697", "name" => "PIERNA PERNIL CON RABADILLA", "stock" => "0", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "51", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "9500", "price_insti" => "9500", "price_horeca" => "12000", "price_hogar" => "12000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0010", "barcode" => "323456698", "name" => "COLOMBINA CON", "stock" => "0", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "55", "unitofmeasure_id" => "1", "cost" => "13000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0011", "barcode" => "323456699", "name" => "MUSLITOS CON", "stock" => "0", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "55", "unitofmeasure_id" => "1", "cost" => "13500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0012", "barcode" => "323456700", "name" => "PIERNA PERNIL SIN RABADILLA", "stock" => "0", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "52", "unitofmeasure_id" => "1", "cost" => "14000", "price_fama" => "11000", "price_insti" => "11000", "price_horeca" => "13000", "price_hogar" => "13000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0013", "barcode" => "323456701", "name" => "COLOMBINA SIN", "stock" => "0", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "52", "unitofmeasure_id" => "1", "cost" => "14500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0014", "barcode" => "323456702", "name" => "MUSLITOS SIN", "stock" => "0", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "53", "unitofmeasure_id" => "1", "cost" => "10000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0015", "barcode" => "323456703", "name" => "POLLO ENTERO BLANCO", "stock" => "0", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "53", "unitofmeasure_id" => "1", "cost" => "10500", "price_fama" => "11700", "price_insti" => "11700", "price_horeca" => "14000", "price_hogar" => "14000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0016", "barcode" => "323456704", "name" => "PECHUGA MARINADA", "stock" => "0", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "54", "unitofmeasure_id" => "1", "cost" => "11000", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0017", "barcode" => "323456705", "name" => "PIERNA PERNIL MARINADA", "stock" => "0", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "55", "unitofmeasure_id" => "1", "cost" => "11500", "price_fama" => "0", "price_insti" => "0", "price_horeca" => "0", "price_hogar" => "0", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0018", "barcode" => "323456706", "name" => "MENUDENCIA DE POLLO", "stock" => "0", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "55", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "2700", "price_insti" => "2700", "price_horeca" => "2100", "price_hogar" => "2100", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0019", "barcode" => "323456707", "name" => "CORAZON DE POLLO", "stock" => "0", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "55", "unitofmeasure_id" => "1", "cost" => "12000", "price_fama" => "9400", "price_insti" => "9400", "price_horeca" => "0", "price_hogar" => "9400", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();
        $product = new Product(["code" => "PO0020", "barcode" => "323456708", "name" => "MOLLEJA POLLO", "stock" => "0", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "55", "unitofmeasure_id" => "1", "cost" => "12500", "price_fama" => "9400", "price_insti" => "9400", "price_horeca" => "0", "price_hogar" => "9400", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]);
        $product->save();


        //POLLO


    }
}
