<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $product = new Product(["code"=> "PC001", "barcode" => "123456689", "name" => "PACHA", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "1", "unitofmeasure_id" => "1", "cost" => "10000", "price" => "12000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC002", "barcode" => "123456690", "name" => "CENTRO DE PIERNA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "1", "unitofmeasure_id" => "1", "cost" => "10500", "price" => "12500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC003", "barcode" => "123456691", "name" => "SIRLOIN DE RES", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "1", "unitofmeasure_id" => "1", "cost" => "11000", "price" => "13000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC004", "barcode" => "123456692", "name" => "BOTA CON MUCHACHO", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "1", "unitofmeasure_id" => "1", "cost" => "11500", "price" => "13500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC005", "barcode" => "123456693", "name" => "CAMPANA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "1", "unitofmeasure_id" => "1", "cost" => "12000", "price" => "14000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC006", "barcode" => "123456694", "name" => "BOTA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "1", "unitofmeasure_id" => "1", "cost" => "12000", "price" => "14000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC007", "barcode" => "123456695", "name" => "ASAR ESPECIAL", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "1", "unitofmeasure_id" => "1", "cost" => "12500", "price" => "14500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC008", "barcode" => "123456696", "name" => "MUCHACHO", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "1", "unitofmeasure_id" => "1", "cost" => "12500", "price" => "14500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC009", "barcode" => "123456697", "name" => "CADERA COMPLETA", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "13000", "price" => "15000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC010", "barcode" => "123456698", "name" => "CADERA SIN PUNTA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "13500", "price" => "15500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC011", "barcode" => "123456699", "name" => "MINI CHURASCO DE CADERA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "14000", "price" => "16000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC012", "barcode" => "123456700", "name" => "PUNTA DE ANCA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "2", "unitofmeasure_id" => "1", "cost" => "14500", "price" => "16500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC013", "barcode" => "123456701", "name" => "BOLA DE PIERNA", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "3", "unitofmeasure_id" => "1", "cost" => "15000", "price" => "17000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC014", "barcode" => "123456702", "name" => "CHATA COMPLETA", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "15500", "price" => "17500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC015", "barcode" => "123456703", "name" => "CHATA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "16000", "price" => "18000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC016", "barcode" => "123456704", "name" => "CHURRASCO", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "4", "unitofmeasure_id" => "1", "cost" => "16500", "price" => "18500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC017", "barcode" => "123456705", "name" => "LOMO ENTERO", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "5", "unitofmeasure_id" => "1", "cost" => "17000", "price" => "19000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC018", "barcode" => "123456706", "name" => "LOMO FINO LIMPIO", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "5", "unitofmeasure_id" => "1", "cost" => "17500", "price" => "19500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC019", "barcode" => "123456707", "name" => "BRAZO COMPLETO", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "6", "unitofmeasure_id" => "1", "cost" => "18000", "price" => "20000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC020", "barcode" => "123456708", "name" => "BOLA DE BRAZO", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "6", "unitofmeasure_id" => "1", "cost" => "18000", "price" => "20000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC021", "barcode" => "123456709", "name" => "MINI PUNTA DE ANCA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "6", "unitofmeasure_id" => "1", "cost" => "18500", "price" => "20500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC022", "barcode" => "123456710", "name" => "FINA TAJADA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "6", "unitofmeasure_id" => "1", "cost" => "19000", "price" => "21000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC023", "barcode" => "123456711", "name" => "DESCARGUE COMPLETO", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "7", "unitofmeasure_id" => "1", "cost" => "19000", "price" => "21000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC024", "barcode" => "123456712", "name" => "MILANESA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "7", "unitofmeasure_id" => "1", "cost" => "19000", "price" => "21000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC025", "barcode" => "123456713", "name" => "LOMO BARCINO", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "7", "unitofmeasure_id" => "1", "cost" => "20000", "price" => "22000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC026", "barcode" => "123456714", "name" => "CARNE PARA SUDAR", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "7", "unitofmeasure_id" => "1", "cost" => "12000", "price" => "14000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC027", "barcode" => "123456715", "name" => "CARNE BLANDA PARA ASAR", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "7", "unitofmeasure_id" => "1", "cost" => "12000", "price" => "14000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC028", "barcode" => "123456716", "name" => "PECHO CON TAPA", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "20500", "price" => "22500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC029", "barcode" => "123456717", "name" => "PECHO SIN TAPA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "21000", "price" => "23000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC030", "barcode" => "123456718", "name" => "PECHO SIN TAPA SIN BOTON", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "21500", "price" => "23500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC031", "barcode" => "123456719", "name" => "TAPA ", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "22000", "price" => "24000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC032", "barcode" => "123456720", "name" => "BOTON", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "22500", "price" => "24500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC033", "barcode" => "123456721", "name" => "CARNE PARA DESMECHAR", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "8", "unitofmeasure_id" => "1", "cost" => "22500", "price" => "24500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC034", "barcode" => "123456722", "name" => "MURILLO", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "9", "unitofmeasure_id" => "1", "cost" => "23000", "price" => "25000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC035", "barcode" => "123456723", "name" => "MURILLO PIERNA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "9", "unitofmeasure_id" => "1", "cost" => "23500", "price" => "25500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC036", "barcode" => "123456724", "name" => "COGOTE", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "10", "unitofmeasure_id" => "1", "cost" => "24000", "price" => "26000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC037", "barcode" => "123456725", "name" => "CARNE GOULASH", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "10", "unitofmeasure_id" => "1", "cost" => "24500", "price" => "26500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC038", "barcode" => "123456726", "name" => "MOLIDA ESPECIAL", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "10", "unitofmeasure_id" => "1", "cost" => "25000", "price" => "27000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC039", "barcode" => "123456727", "name" => "COSTILLA DELANTERA", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "11", "unitofmeasure_id" => "1", "cost" => "25500", "price" => "27500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC040", "barcode" => "123456728", "name" => "ASADO DE TIRA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "11", "unitofmeasure_id" => "1", "cost" => "26000", "price" => "28000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC041", "barcode" => "123456729", "name" => "COSTILLA SUPER ESPECIAL", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "11", "unitofmeasure_id" => "1", "cost" => "26500", "price" => "28500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC042", "barcode" => "123456730", "name" => "COSTILLA COMPLETA", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "27000", "price" => "29000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC043", "barcode" => "123456731", "name" => "COSTILLA CANASTO", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "27500", "price" => "29500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC044", "barcode" => "123456732", "name" => "COSTILLA ESPECIAL", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "28000", "price" => "30000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC045", "barcode" => "123456733", "name" => "COSTILLA CORRIENTE", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "28500", "price" => "30500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC046", "barcode" => "123456734", "name" => "FALDA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "29000", "price" => "31000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC047", "barcode" => "123456735", "name" => "PALOMILLA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "29000", "price" => "31000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC048", "barcode" => "123456736", "name" => "SOBREBARRIGA GRUESA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "29500", "price" => "31500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC049", "barcode" => "123456737", "name" => "SOBREBARRIGA DELGADA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "12", "unitofmeasure_id" => "1", "cost" => "30000", "price" => "32000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC050", "barcode" => "123456738", "name" => "COLA DE RES ENTERA", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "13", "unitofmeasure_id" => "1", "cost" => "30500", "price" => "32500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC051", "barcode" => "123456739", "name" => "NUDOS DE COLA", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "13", "unitofmeasure_id" => "1", "cost" => "31000", "price" => "33000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC052", "barcode" => "123456740", "name" => "HUESO DE PALETA", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "14", "unitofmeasure_id" => "1", "cost" => "31500", "price" => "33500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC053", "barcode" => "123456741", "name" => "TOMAHAWK-TBONE", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "15", "unitofmeasure_id" => "1", "cost" => "32000", "price" => "34000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC054", "barcode" => "123456742", "name" => "HUESO ESPECIAL", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "16", "unitofmeasure_id" => "1", "cost" => "32500", "price" => "34500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC055", "barcode" => "123456743", "name" => "HUESO AGUJA", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "17", "unitofmeasure_id" => "1", "cost" => "33000", "price" => "35000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC056", "barcode" => "123456744", "name" => "HUESO CARNUDO", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "18", "unitofmeasure_id" => "1", "cost" => "33500", "price" => "35500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC057", "barcode" => "123456745", "name" => "HUESO DE PECHO", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "19", "unitofmeasure_id" => "1", "cost" => "34000", "price" => "36000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC058", "barcode" => "123456746", "name" => "VIRILIS", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "20", "unitofmeasure_id" => "1", "cost" => "34500", "price" => "36500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC059", "barcode" => "123456747", "name" => "CREADILLAS", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "21", "unitofmeasure_id" => "1", "cost" => "35000", "price" => "37000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC060", "barcode" => "123456748", "name" => "SEBO PECHO", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "22", "unitofmeasure_id" => "1", "cost" => "35500", "price" => "37500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC061", "barcode" => "123456749", "name" => "SEBO ", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "23", "unitofmeasure_id" => "1", "cost" => "36000", "price" => "38000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC062", "barcode" => "123456750", "name" => "HUESO POROSO", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "24", "unitofmeasure_id" => "1", "cost" => "36500", "price" => "38500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC063", "barcode" => "123456751", "name" => "MOTA", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "25", "unitofmeasure_id" => "1", "cost" => "37000", "price" => "39000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC064", "barcode" => "123456752", "name" => "MOLIDA CORRIENTE", "stock" => "10", "category_id" => "1", "level_product_id" => "2", "meatcut_id" => "25", "unitofmeasure_id" => "1", "cost" => "37500", "price" => "39500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC065", "barcode" => "123456753", "name" => "CHOCOZUELA", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "26", "unitofmeasure_id" => "1", "cost" => "38000", "price" => "40000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC066", "barcode" => "123456754", "name" => "RILA", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "27", "unitofmeasure_id" => "1", "cost" => "38500", "price" => "40500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
        $product = new Product(["code"=> "PC067", "barcode" => "123456755", "name" => "UBRE", "stock" => "10", "category_id" => "1", "level_product_id" => "1", "meatcut_id" => "28", "unitofmeasure_id" => "1", "cost" => "39000", "price" => "41000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();
//CERDO
        $product = new Product(["code"=> "PC200", "barcode" => "223456755", "name" => "ESPINAZO DE CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "31", "unitofmeasure_id" => "1", "cost" => "10000", "price" => "12000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC201", "barcode" => "223456756", "name" => "COSTILOMO COMPLETO", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "32", "unitofmeasure_id" => "1", "cost" => "10500", "price" => "12500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC202", "barcode" => "223456757", "name" => "CHULETA DE LOMO", "stock" => "10", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "32", "unitofmeasure_id" => "1", "cost" => "11000", "price" => "13000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC203", "barcode" => "223456758", "name" => "COSTILLA DE CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "32", "unitofmeasure_id" => "1", "cost" => "11500", "price" => "13500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC204", "barcode" => "223456759", "name" => "COSTILLA SPARRY", "stock" => "10", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "32", "unitofmeasure_id" => "1", "cost" => "12000", "price" => "14000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC205", "barcode" => "223456760", "name" => "COSTILLA BABY BACK DE CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "32", "unitofmeasure_id" => "1", "cost" => "12500", "price" => "14500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC206", "barcode" => "223456761", "name" => "SOLOMITO DE CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "32", "unitofmeasure_id" => "1", "cost" => "13000", "price" => "15000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC207", "barcode" => "223456762", "name" => "CABEZA DE CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "33", "unitofmeasure_id" => "1", "cost" => "13500", "price" => "15500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC208", "barcode" => "223456763", "name" => "TOCINO BARRIGA", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "34", "unitofmeasure_id" => "1", "cost" => "14000", "price" => "16000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC209", "barcode" => "223456764", "name" => "TOCINO PAPADA", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "35", "unitofmeasure_id" => "1", "cost" => "14500", "price" => "16500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC210", "barcode" => "223456765", "name" => "PEZUÑA DE CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "36", "unitofmeasure_id" => "1", "cost" => "15000", "price" => "17000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC211", "barcode" => "223456766", "name" => "DORSAL - TOCINO CORRIENTE", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "37", "unitofmeasure_id" => "1", "cost" => "15500", "price" => "17500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC212", "barcode" => "223456767", "name" => "EMPELLA - DESPALME", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "38", "unitofmeasure_id" => "1", "cost" => "16000", "price" => "18000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC213", "barcode" => "223456768", "name" => "PERNIL DE CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "39", "unitofmeasure_id" => "1", "cost" => "16500", "price" => "18500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC214", "barcode" => "223456769", "name" => "SIRLOIN DE CERDO ", "stock" => "10", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "39", "unitofmeasure_id" => "1", "cost" => "17000", "price" => "19000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC215", "barcode" => "223456770", "name" => "PULPA DE PIERNA CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "39", "unitofmeasure_id" => "1", "cost" => "17500", "price" => "19500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC216", "barcode" => "223456771", "name" => "CHULETA DE PIERNA", "stock" => "10", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "39", "unitofmeasure_id" => "1", "cost" => "18000", "price" => "20000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC217", "barcode" => "223456772", "name" => "BRAZO DE CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "40", "unitofmeasure_id" => "1", "cost" => "18500", "price" => "20500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC218", "barcode" => "223456773", "name" => "PULPA DE BRAZO CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "40", "unitofmeasure_id" => "1", "cost" => "19000", "price" => "21000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC219", "barcode" => "223456774", "name" => "CHULETA DE BRAZO", "stock" => "10", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "40", "unitofmeasure_id" => "1", "cost" => "19500", "price" => "21500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC220", "barcode" => "223456775", "name" => "MILANESA DE CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "40", "unitofmeasure_id" => "1", "cost" => "20000", "price" => "22000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC221", "barcode" => "223456776", "name" => "GOULASH DE CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "40", "unitofmeasure_id" => "1", "cost" => "20500", "price" => "22500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC222", "barcode" => "223456777", "name" => "HUESO POROSO DE CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "41", "unitofmeasure_id" => "1", "cost" => "21000", "price" => "23000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC223", "barcode" => "223456778", "name" => "BONDIOLA", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "42", "unitofmeasure_id" => "1", "cost" => "21500", "price" => "23500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC224", "barcode" => "223456779", "name" => "PANCETA", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "43", "unitofmeasure_id" => "1", "cost" => "22000", "price" => "24000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC225", "barcode" => "223456780", "name" => "MATAMBRE", "stock" => "10", "category_id" => "2", "level_product_id" => "2", "meatcut_id" => "43", "unitofmeasure_id" => "1", "cost" => "22500", "price" => "24500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC226", "barcode" => "223456781", "name" => "OSSOBUCO + CODO", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "44", "unitofmeasure_id" => "1", "cost" => "23000", "price" => "25000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC227", "barcode" => "223456782", "name" => "LOMO DE CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "45", "unitofmeasure_id" => "1", "cost" => "23500", "price" => "25500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC228", "barcode" => "223456783", "name" => "MOTA DE CERDO", "stock" => "10", "category_id" => "2", "level_product_id" => "1", "meatcut_id" => "46", "unitofmeasure_id" => "1", "cost" => "24000", "price" => "26000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								                              
 //POLLO                                       
        $product = new Product(["code"=> "PC300", "barcode" => "323456689", "name" => "PECHUGA", "stock" => "10", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "51", "unitofmeasure_id" => "1", "cost" => "13000", "price" => "15000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC301", "barcode" => "323456690", "name" => "PIERNA PERNIL, CON RABADILLA", "stock" => "10", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "52", "unitofmeasure_id" => "1", "cost" => "13500", "price" => "15500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC302", "barcode" => "323456691", "name" => "PIERNA PERNIL , SIN RABADILLA", "stock" => "10", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "52", "unitofmeasure_id" => "1", "cost" => "14000", "price" => "16000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC303", "barcode" => "323456692", "name" => "COLOMBINAS", "stock" => "10", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "52", "unitofmeasure_id" => "1", "cost" => "13000", "price" => "15000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC304", "barcode" => "323456693", "name" => "MUSLITOS", "stock" => "10", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "52", "unitofmeasure_id" => "1", "cost" => "13500", "price" => "15500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC305", "barcode" => "323456694", "name" => "MIXTO", "stock" => "10", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "52", "unitofmeasure_id" => "1", "cost" => "14000", "price" => "16000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC306", "barcode" => "323456695", "name" => "ALAS, CON COSTILLAR", "stock" => "10", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "53", "unitofmeasure_id" => "1", "cost" => "13000", "price" => "15000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC307", "barcode" => "323456696", "name" => "ALAS, SIN COSTILLAR", "stock" => "10", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "53", "unitofmeasure_id" => "1", "cost" => "13500", "price" => "15500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC308", "barcode" => "323456697", "name" => "COSTILLARES # 1", "stock" => "10", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "53", "unitofmeasure_id" => "1", "cost" => "14000", "price" => "16000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC309", "barcode" => "323456698", "name" => "COSTILLARES # 2", "stock" => "10", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "53", "unitofmeasure_id" => "1", "cost" => "13000", "price" => "15000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC310", "barcode" => "323456699", "name" => "GRASA", "stock" => "10", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "54", "unitofmeasure_id" => "1", "cost" => "13500", "price" => "15500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC311", "barcode" => "323456700", "name" => "POLLO ENTERO", "stock" => "10", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "55", "unitofmeasure_id" => "1", "cost" => "14000", "price" => "16000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC312", "barcode" => "323456701", "name" => "VISCERAS", "stock" => "10", "category_id" => "3", "level_product_id" => "1", "meatcut_id" => "56", "unitofmeasure_id" => "1", "cost" => "13000", "price" => "15000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC313", "barcode" => "323456702", "name" => "MENUDENCIAS", "stock" => "10", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "56", "unitofmeasure_id" => "1", "cost" => "13500", "price" => "15500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC314", "barcode" => "323456703", "name" => "MOLLEJAS", "stock" => "10", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "56", "unitofmeasure_id" => "1", "cost" => "14000", "price" => "16000", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
        $product = new Product(["code"=> "PC315", "barcode" => "323456704", "name" => "CORAZONES", "stock" => "10", "category_id" => "3", "level_product_id" => "2", "meatcut_id" => "56", "unitofmeasure_id" => "1", "cost" => "13500", "price" => "15500", "iva" => "0", "alerts" => "10", "image" => "noimage.png"]); $product->save();								
      
    }
}
