<?php

namespace Database\Seeders;

use App\Models\Third;
use Illuminate\Database\Seeder;

class ThirdSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */

  public function run()
  {
    $third = new Third(["name" => "INVERSIONES MORACA SAS", "type_identification_id" => "1", "identification" => "901510487", "digito_verificacion" => "1", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "AUTO SUR 66 78 LC B15", "province_id" => "6", "celular" => "3205648821", "nombre_contacto" => "EDWIN JARAMILLO", "status" => "1", "correo" => "eonardomoralescadena@gmail.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "BAIRON ALEXIS MORENO RAMIREZ", "type_identification_id" => "2", "identification" => "102456599", "digito_verificacion" => "6", "office_id" => "2", "type_regimen_iva_id" => "2", "direccion" => "CR 43A 68B SUR 15CA", "province_id" => "6", "celular" => "3212022758", "nombre_contacto" => "BAIRON ALEXIS MORENO RAMIREZ", "status" => "1", "correo" => "elplumablanca2022@gmail.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "4", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "LUISA FERNANDA OCHOA HERRERA", "type_identification_id" => "2", "identification" => "1000993554", "digito_verificacion" => "1", "office_id" => "2", "type_regimen_iva_id" => "2", "direccion" => "Ak 45A 62D 104", "province_id" => "6", "celular" => "3132877358", "nombre_contacto" => "LUISA FERNANDA OCHOA HERRERA", "status" => "1", "correo" => "violetaoh6@hotmail.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "MEGACHORIZOS SAS", "type_identification_id" => "1", "identification" => "900490684", "digito_verificacion" => "3", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "AUTO SUR 66 78 LC C28", "province_id" => "6", "celular" => "3125948706", "nombre_contacto" => "MEGACHORIZOS SAS", "status" => "1", "correo" => "megachorizos@gmail.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "VICTOR MANUEL MARTIN URREGO", "type_identification_id" => "2", "identification" => "3032710", "digito_verificacion" => "1", "office_id" => "2", "type_regimen_iva_id" => "2", "direccion" => "AUTO SUR 66 78 OF 101", "province_id" => "6", "celular" => "3202231308", "nombre_contacto" => "VICTOR MANUEL MARTIN URREGO", "status" => "1", "correo" => "victormartin@gmail.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "COMERCIALIZADORA Y PROCESADORA PRODISPIELES FRESCAS SAS", "type_identification_id" => "1", "identification" => "901516847", "digito_verificacion" => "5", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "AUT SUR 66 78 OF 313", "province_id" => "6", "celular" => "31383", "nombre_contacto" => "OSCAR MARTINEZ", "status" => "1", "correo" => "facturacionprodispieles@gmail.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "EULISES PRADA BLANCO", "type_identification_id" => "2", "identification" => "1104184376", "digito_verificacion" => "1", "office_id" => "2", "type_regimen_iva_id" => "2", "direccion" => "AUT SUR 66 78 CL D 12 BRR GUADALUPE", "province_id" => "6", "celular" => "3209907761", "nombre_contacto" => "EULISES PRADA BLANCO", "status" => "1", "correo" => "viscerassantander@hotmail.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "DISTRIBUIDORA DE CARNES EL PARAISO SAS", "type_identification_id" => "1", "identification" => "901419267", "digito_verificacion" => "8", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "AUTO SUR 66 78 LC C29", "province_id" => "6", "celular" => "3115754934", "nombre_contacto" => "EL PARAISO", "status" => "1", "correo" => "carneselparaiso@hotmail.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "COMERCIALIZADORA DE PESCADOS GARCIPEZ EU", "type_identification_id" => "1", "identification" => "900197840", "digito_verificacion" => "0", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "AUTOPISTA SUR 66 78 LC B10", "province_id" => "6", "celular" => "7284241", "nombre_contacto" => "GARCIPEZ", "status" => "1", "correo" => "garcipez@gmail.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "AVICOLA LOS CAMBULOS SAS", "type_identification_id" => "1", "identification" => "860058831", "digito_verificacion" => "4", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "Auto sur 66 78 LC C14", "province_id" => "6", "celular" => "3102547989", "nombre_contacto" => "CAMBULOS", "status" => "1", "correo" => "info@avicambulos.com.co", "cliente" => "1", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "3", "listaprecio_genericid" => "17"]);
    $third->save();
    $third = new Third(["name" => "VODINOS SAS", "type_identification_id" => "1", "identification" => "901593954", "digito_verificacion" => "3", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "AUTOPISTA SUR 66 78 LC C03", "province_id" => "6", "celular" => "3143472987", "nombre_contacto" => "VODINOS", "status" => "1", "correo" => "vodinos@gmail.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "POLLO FIESTA SA", "type_identification_id" => "1", "identification" => "860032450", "digito_verificacion" => "9", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "CR 68 D 12 37", "province_id" => "6", "celular" => "4172450", "nombre_contacto" => "IVAN ROMERO", "status" => "1", "correo" => "contacto@pollo-fiesta.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "COMPAÑIA INTERNACIONAL DE ALIMENTOS PETRA FOODS SAS", "type_identification_id" => "1", "identification" => "901567065", "digito_verificacion" => "0", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "AUTO SUR 66 78  LC A17", "province_id" => "6", "celular" => "3133872711", "nombre_contacto" => "ALEJANDRO MARTINEZ", "status" => "1", "correo" => "laroca@gmail.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "18", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "INVERSIONES GANADERAS DEL META SAS", "type_identification_id" => "1", "identification" => "900385837", "digito_verificacion" => "4", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "AUTOPISTA SUR 66 78 LC B6 B7", "province_id" => "6", "celular" => "2704572", "nombre_contacto" => "OSCAR MARTINEZ", "status" => "1", "correo" => "contactenos@noova.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "INVERSIONES MUÑOZ CASALLAS SAS", "type_identification_id" => "1", "identification" => "901492211", "digito_verificacion" => "0", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "AUTO SUR 6678 LC C05", "province_id" => "6", "celular" => "3015108788", "nombre_contacto" => "MUÑOZ", "status" => "1", "correo" => "facturainvmunoz@gmail.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "ELSA MARIA ALFONSO OVALLE", "type_identification_id" => "2", "identification" => "23424243", "digito_verificacion" => "7", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "CR 5 6 70", "province_id" => "6", "celular" => "3185438769", "nombre_contacto" => "ELSA ALFONSO", "status" => "1", "correo" => "alfonsoelsamaria115@gmail.com", "cliente" => "0", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "5"]);
    $third->save();
    $third = new Third(["name" => "GRUPO GUMAR SAS", "type_identification_id" => "1", "identification" => "900545594", "digito_verificacion" => "7", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "CALLE 23 #97-46", "province_id" => "6", "celular" => "6014673630", "nombre_contacto" => "JHON LOPEZ", "status" => "1", "correo" => "grupogimar@gmail.com", "cliente" => "0", "proveedor" => "1", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "0"]);
    $third->save();
    $third = new Third(["name" => "COMERCIALIZADORA NACIONAL DE CARNICOS SAS", "type_identification_id" => "1", "identification" => "900582769", "digito_verificacion" => "6", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "AUTO SUR 66-78 LC B101", "province_id" => "6", "celular" => "6017282378", "nombre_contacto" => "ALIMENTAR BEEF", "status" => "1", "correo" => "juridica@alimentarbeffmarket.com", "cliente" => "0", "proveedor" => "1", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "0"]);
    $third->save();
    $third = new Third(["name" => "AVIDESA MACPOLLO SA", "type_identification_id" => "1", "identification" => "890201881", "digito_verificacion" => "4", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "CARRERA 34 19A-69", "province_id" => "6", "celular" => "312400005", "nombre_contacto" => "PUNTO DE VENTA", "status" => "1", "correo" => "serviclientes@macpollo.com", "cliente" => "0", "proveedor" => "1", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "2", "listaprecio_genericid" => "0"]);
    $third->save();
    $third = new Third(["name" => "COLOMBIANA DE COMERCIO SA", "type_identification_id" => "1", "identification" => "890900943", "digito_verificacion" => "1", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "Calle 45c sur ", "province_id" => "6", "celular" => "4376868", "nombre_contacto" => "ALKOSTO ", "status" => "1", "correo" => "vozcliente@alkosto.com.co", "cliente" => "0", "proveedor" => "1", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "0"]);
    $third->save();
    $third = new Third(["name" => "CARLOS ALIRIO DEL CAMPO GARCIA", "type_identification_id" => "2", "identification" => "93089133", "digito_verificacion" => "2", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "AUT SUR 66 78LC D03", "province_id" => "6", "celular" => "3107859751", "nombre_contacto" => "CARLOS DEL CAMPO", "status" => "1", "correo" => "viscerassancarlos@gmail.com", "cliente" => "0", "proveedor" => "1", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "0"]);
    $third->save();
    $third = new Third(["name" => "Wolfran Ernesto Suarez Oliveros", "type_identification_id" => "2", "identification" => "1030617050", "digito_verificacion" => "8", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "CL 26 SUR 95 A 49", "province_id" => "6", "celular" => "3123144156", "nombre_contacto" => "Wolfran Ernesto Suarez Oliveros", "status" => "1", "correo" => "wolfransuarez1030@gmail.com", "cliente" => "0", "proveedor" => "1", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "0"]);
    $third->save();
    $third = new Third(["name" => "POLLOS FAMICOL SAS", "type_identification_id" => "1", "identification" => "901451741", "digito_verificacion" => "2", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "CR 62 D 57 D 63 SUR", "province_id" => "6", "celular" => "31048114811", "nombre_contacto" => "FAMICOL", "status" => "1", "correo" => "pollosfamicol@gmail.com", "cliente" => "0", "proveedor" => "1", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "0"]);
    $third->save();
    $third = new Third(["name" => "CARNES BONANZA JEV SAS", "type_identification_id" => "1", "identification" => "901338422", "digito_verificacion" => "5", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "AUTO SUR 66 78 LOCAL A 24", "province_id" => "6", "celular" => "3023893323", "nombre_contacto" => "BONANZA", "status" => "1", "correo" => "carnesbonanza1990@hotmail.com", "cliente" => "0", "proveedor" => "1", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "0"]);
    $third->save();
    $third = new Third(["name" => "INCORAVI SAS", "type_identification_id" => "1", "identification" => "900207430", "digito_verificacion" => "9", "office_id" => "2", "type_regimen_iva_id" => "2", "direccion" => "AUTO SUR 66-78 LB17/C17", "province_id" => "6", "celular" => "3246218106", "nombre_contacto" => "NEILA PEINADO", "status" => "1", "correo" => "compras@puracarnes.com", "cliente" => "0", "proveedor" => "1", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "0"]);
    $third->save();
    $third = new Third(["name" => "14 INKAS SA", "type_identification_id" => "1", "identification" => "900209731", "digito_verificacion" => "1", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "CALLE 74 #5-28 NAZCA", "province_id" => "6", "celular" => "6016230555", "nombre_contacto" => "14 INKAS SA", "status" => "1", "correo" => "facturacion14inkas@gruponazca.com.co", "cliente" => "1", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "0", "listaprecio_genericid" => "10"]);
    $third->save();
    $third = new Third(["name" => "COMERCIALIZADORA DE ALIMENTOS RAMDI", "type_identification_id" => "1", "identification" => "830031970", "digito_verificacion" => "3", "office_id" => "2", "type_regimen_iva_id" => "2", "direccion" => "CARRERA 17 #164-57", "province_id" => "6", "celular" => "3208588700", "nombre_contacto" => "ALVARO ", "status" => "1", "correo" => "ramdicarnes@yahoo.com", "cliente" => "1", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "9", "listaprecio_genericid" => "9"]);
    $third->save();
    $third = new Third(["name" => "CORPORACIÓN EDUCATIVA MINUTO DE DIOS CEMID", "type_identification_id" => "1", "identification" => "800215465", "digito_verificacion" => "7", "office_id" => "2", "type_regimen_iva_id" => "2", "direccion" => "CALLE 81 #73B-16 PISO1", "province_id" => "6", "celular" => "6015933040", "nombre_contacto" => "FACTURACION", "status" => "1", "correo" => "facturacion@colegiosminutodedios.edu.co", "cliente" => "1", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "8", "listaprecio_genericid" => "8"]);
    $third->save();
    $third = new Third(["name" => "CASINO CENTRAL DE SUBOFICIALES DE LA FUERZA AEREA COLOMBIANA", "type_identification_id" => "1", "identification" => "900518176", "digito_verificacion" => "7", "office_id" => "2", "type_regimen_iva_id" => "1", "direccion" => "CARRERA 61 #96-02", "province_id" => "6", "celular" => "3045721342", "nombre_contacto" => "ANDRES NOVA", "status" => "1", "correo" => "compras.ccsfac@fac.mil.co", "cliente" => "1", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "11", "listaprecio_genericid" => "11"]);
    $third->save();
    $third = new Third(["name" => "MILAGRO PEÑA MARTINEZ", "type_identification_id" => "2", "identification" => "1048205590", "digito_verificacion" => "0", "office_id" => "2", "type_regimen_iva_id" => "2", "direccion" => "CARRERA 79 #19A-28 TORRE 2 APT 301", "province_id" => "6", "celular" => "3044228481", "nombre_contacto" => "MILAGRO PEÑA", "status" => "1", "correo" => "milagropena398@gmail.com", "cliente" => "1", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "5", "domiciliario" => "0", "listaprecio_nichoid" => "1", "listaprecio_genericid" => "0"]);
    $third->save();
    $third = new Third(["name" => "YEFFERSON YOSUE MIRANDA MENDEZ", "type_identification_id" => "3", "identification" => "5453393", "digito_verificacion" => "0", "office_id" => "2", "type_regimen_iva_id" => "2", "direccion" => "CALLE 49B #13A-32", "province_id" => "6", "celular" => "3229069391", "nombre_contacto" => "YEFFERSON MIRANDA", "status" => "1", "correo" => "jeffersonmiranda@gmail.com", "cliente" => "1", "proveedor" => "0", "vendedor" => "1", "porc_descuento" => "0", "domiciliario" => "0", "listaprecio_nichoid" => "1", "listaprecio_genericid" => "0"]);
    $third->save();
    $third = new Third(["name" => "HECTOR FABIO NIEVES FONSECA", "type_identification_id" => "2", "identification" => "1026553049", "digito_verificacion" => "0", "office_id" => "2", "type_regimen_iva_id" => "2", "direccion" => "CALLE 71 SUR #98B-50 BOSA RECREO", "province_id" => "6", "celular" => "3160443188", "nombre_contacto" => "HECTOR NIEVES", "status" => "1", "correo" => "temporal@temporal.com", "cliente" => "1", "proveedor" => "0", "vendedor" => "0", "porc_descuento" => "0", "domiciliario" => "1", "listaprecio_nichoid" => "1", "listaprecio_genericid" => "0"]);
    $third->save();
  }
}
